config/routes.rb
Rails.application.routes.draw do
  resources :lens_materials
  resources :lens_colors
  resources :frame_colors
  resources :models
  resources :frame_widths
  resources :costs do 
    collection {post :import}
  end
  resources :products do 
  	collection {post :traer_data}
  end
  resources :ebay_auths
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'welcome#index'


    get 'ebay_accept', to: 'welcome#ebay_accept'
    get '/token', to: 'ebay_auths#token'

    get '/productos', to: 'products#productos'
    get '/cargar_listings', to: 'products#cargar_listings'


    ### api 

    get '/get_item', to: 'ebay_auths#get_item'
    
    
end

app/models/lens_material.rb
class LensMaterial < ApplicationRecord
	belongs_to :lens_color
end

app/controllers/lens_materials_controller.rb
class LensMaterialsController < ApplicationController
  before_action :set_lens_material, only: [:show, :edit, :update, :destroy]

  # GET /lens_materials
  # GET /lens_materials.json
  def index
    @lens_materials = LensMaterial.all
  end

  # GET /lens_materials/1
  # GET /lens_materials/1.json
  def show
  end

  # GET /lens_materials/new
  def new
    @lens_material = LensMaterial.new
  end

  # GET /lens_materials/1/edit
  def edit
  end

  # POST /lens_materials
  # POST /lens_materials.json
  def create
    @lens_material = LensMaterial.new(lens_material_params)

    respond_to do |format|
      if @lens_material.save
        format.html { redirect_to @lens_material, notice: 'Lens material was successfully created.' }
        format.json { render :show, status: :created, location: @lens_material }
      else
        format.html { render :new }
        format.json { render json: @lens_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lens_materials/1
  # PATCH/PUT /lens_materials/1.json
  def update
    respond_to do |format|
      if @lens_material.update(lens_material_params)
        format.html { redirect_to @lens_material, notice: 'Lens material was successfully updated.' }
        format.json { render :show, status: :ok, location: @lens_material }
      else
        format.html { render :edit }
        format.json { render json: @lens_material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lens_materials/1
  # DELETE /lens_materials/1.json
  def destroy
    @lens_material.destroy
    respond_to do |format|
      format.html { redirect_to lens_materials_url, notice: 'Lens material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lens_material
      @lens_material = LensMaterial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lens_material_params
      params.require(:lens_material).permit(:frame_width_id, :frame_color_id, :model_id, :lens_color_id, :name)
    end
end

app/helpers/lens_materials_helper.rb
module LensMaterialsHelper
end

app/views/lens_materials/_form.html.erb
<%= form_with(model: lens_material, local: true) do |form| %>
  <% if lens_material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lens_material.errors.count, "error") %> prohibited this lens_material from being saved:</h2>

      <ul>
      <% lens_material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :frame_width_id %>
    <%= form.number_field :frame_width_id %>
  </div>

  <div class="field">
    <%= form.label :frame_color_id %>
    <%= form.number_field :frame_color_id %>
  </div>

  <div class="field">
    <%= form.label :model_id %>
    <%= form.number_field :model_id %>
  </div>

  <div class="field">
    <%= form.label :lens_color_id %>
    <%= form.number_field :lens_color_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lens_materials/edit.html.erb
<h1>Editing Lens Material</h1>

<%= render 'form', lens_material: @lens_material %>

<%= link_to 'Show', @lens_material %> |
<%= link_to 'Back', lens_materials_path %>

app/views/lens_materials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lens Materials</h1>

<table>
  <thead>
    <tr>
      <th>Frame width</th>
      <th>Frame color</th>
      <th>Model</th>
      <th>Lens color</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lens_materials.each do |lens_material| %>
      <tr>
        <td><%= lens_material.frame_width_id %></td>
        <td><%= lens_material.frame_color_id %></td>
        <td><%= lens_material.model_id %></td>
        <td><%= lens_material.lens_color_id %></td>
        <td><%= lens_material.name %></td>
        <td><%= link_to 'Show', lens_material %></td>
        <td><%= link_to 'Edit', edit_lens_material_path(lens_material) %></td>
        <td><%= link_to 'Destroy', lens_material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lens Material', new_lens_material_path %>

app/views/lens_materials/new.html.erb
<h1>New Lens Material</h1>

<%= render 'form', lens_material: @lens_material %>

<%= link_to 'Back', lens_materials_path %>

app/views/lens_materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Frame width:</strong>
  <%= @lens_material.frame_width_id %>
</p>

<p>
  <strong>Frame color:</strong>
  <%= @lens_material.frame_color_id %>
</p>

<p>
  <strong>Model:</strong>
  <%= @lens_material.model_id %>
</p>

<p>
  <strong>Lens color:</strong>
  <%= @lens_material.lens_color_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @lens_material.name %>
</p>

<%= link_to 'Edit', edit_lens_material_path(@lens_material) %> |
<%= link_to 'Back', lens_materials_path %>