config/routes.rb
Rails.application.routes.draw do
  resources :lens_materials
  resources :lens_colors
  resources :frame_colors
  resources :models
  resources :frame_widths
  resources :costs do 
    collection {post :import}
  end
  resources :products do 
  	collection {post :traer_data}
  end
  resources :ebay_auths
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'welcome#index'


    get 'ebay_accept', to: 'welcome#ebay_accept'
    get '/token', to: 'ebay_auths#token'

    get '/productos', to: 'products#productos'
    get '/cargar_listings', to: 'products#cargar_listings'


    ### api 

    get '/get_item', to: 'ebay_auths#get_item'
    
    
end

app/models/ebay_auth.rb
class EbayAuth < ApplicationRecord

	def self.refrescar_token(id)
		ebay_auth = EbayAuth.find(id)
		authorization = ENV.fetch('AUTHORIZATION')
		url_base = "https://api.ebay.com/identity/v1/oauth2/token"

		header    = {"Content-Type" => "application/x-www-form-urlencoded" ,"Authorization" => "Basic #{authorization}"}

		parametros = {"grant_type"=>"refresh_token", "refresh_token" => "#{ebay_auth.refresh_token}"}
		puts parametros

		response = HTTParty.post("#{url_base}", :query => parametros, :headers =>header)

		if response.code == 200
			res = JSON.parse response.body
	  	ebay_auth.access_token = res["access_token"]
	  	ebay_auth.token_type = res["token_type"]
	  	if ebay_auth.save 
	  		puts "se guardo bien "
	  	else
	  		puts "no se guardo nada"
	  	end
	  end

	end

	def self.get_by_upc()


		ebay_auth = EbayAuth.find(1)
		if (Time.now - ebay_auth.updated_at) >= 6600
      ## refresh token
      EbayAuth.refrescar_token(1)
      ebay_auth = EbayAuth.find(1)
    end

    authorization = EbayAuth.find(1).access_token


    productos = Product.all

		productos.each do |p|

			next if p.upc.nil? 
			puts "paso el next"
			puts p.upc
			next if p.upc.to_i == 0 
			ronda = 0
			for i in 0..1
				ronda = i
				upc = p.upc
				upc = "0" + upc if ronda == 1
				url_base = "https://api.ebay.com/buy/browse/v1/item_summary/search?sort=-price&gtin=#{upc}&filter=conditions:{NEW}&limit=100"
				url_base = URI.encode(url_base.strip)
				header    = {"Content-Type" => "application/json" ,"Authorization" => "Bearer #{authorization}"}

				parametros = {}
				puts parametros
				response = HTTParty.get("#{url_base}", :query => parametros, :headers =>header)
				res = JSON.parse response.body

				precios = []
				condiciones = []
				opciones = []

				if res["total"] > 0 
					res["itemSummaries"].each do |p| ### OTRA VEZ P
						if p["conditionId"] == "1000"
							precios << p["price"]["value"].to_f
							condiciones << p["condition"]
							opciones << p["buyingOptions"]
						end
					end
					next if precios.size == 0 
					indice = precios.index(precios.min)
					puts precios
					puts indice
					if ronda == 0 || (ronda == 1 && precios[indice] < p.current_price)
						p.current_price = precios[indice]
						p.url = res["itemSummaries"][indice]["itemWebUrl"]
						costo = Cost.find_by_upc(p.upc)
						if costo.present? 
							p.cost = costo.precio_esp.to_f
							p.gross_margin = p.current_price - costo.precio_esp
							p.net_margin = (p.current_price.to_f*0.88)- 5 - costo.precio_esp.to_f
							p.roi = ((p.net_margin + p.cost)/p.cost)-1
							p.save 
						end
					end
				end
			end ## cierra ronda
		end


	end

end

app/controllers/ebay_auths_controller.rb
class EbayAuthsController < ApplicationController
  before_action :set_ebay_auth, only: [:show, :edit, :update, :destroy]

  # GET /ebay_auths
  # GET /ebay_auths.json
  def index
    @ebay_auths = EbayAuth.all
  end

  # GET /ebay_auths/1
  # GET /ebay_auths/1.json
  def show
  end

  # GET /ebay_auths/new
  def new
    @ebay_auth = EbayAuth.new
  end

  # GET /ebay_auths/1/edit
  def edit
  end

  def token
    puts "entramos en token "
    puts params 
  end

  def get_item

    password = ENV.fetch('PASSWORD')

    salida = {}

    if params["password"].present? && params["password"] == password

      ebay_auth = EbayAuth.find(1)
      ## check expiration
      if (Time.now - ebay_auth.updated_at) >= 6600
        ## refresh token
        EbayAuth.refrescar_token(1)
        ebay_auth = EbayAuth.find(1)
      end

      authorization = EbayAuth.find(1).access_token

      item_id = params["item_id"].to_i
      url_base = "https://api.ebay.com/buy/browse/v1/item/v1|#{item_id}|0"
      url_base = URI.encode(url_base.strip)
      header    = {"Content-Type" => "application/json" ,"Authorization" => "Bearer #{authorization}"}

      parametros = {}
      puts parametros

      response = HTTParty.get("#{url_base}", :query => parametros, :headers =>header)
      if response.code == 200 
        res = JSON.parse response.body
        atributos = res["localizedAspects"]
        upc = "no hay UPC"
        if atributos.present? && atributos.size > 0
          atributos.each do |x|
            if x["name"] =="UPC"
              upc = x["value"]
            end
          end
        end

        salida["UPC"] = upc
      else
        salida["error"] = "item no encontrado"
      end
    else
      salida["error"] = "Acceso no autorizado"
    end

    respond_to do |format|
      puts "entro en get items"
      puts salida
      format.json { render json: salida }
    end
  end

  # POST /ebay_auths
  # POST /ebay_auths.json
  def create
    @ebay_auth = EbayAuth.new(ebay_auth_params)

    respond_to do |format|
      if @ebay_auth.save
        format.html { redirect_to @ebay_auth, notice: 'Ebay auth was successfully created.' }
        format.json { render :show, status: :created, location: @ebay_auth }
      else
        format.html { render :new }
        format.json { render json: @ebay_auth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ebay_auths/1
  # PATCH/PUT /ebay_auths/1.json
  def update
    respond_to do |format|
      if @ebay_auth.update(ebay_auth_params)
        format.html { redirect_to @ebay_auth, notice: 'Ebay auth was successfully updated.' }
        format.json { render :show, status: :ok, location: @ebay_auth }
      else
        format.html { render :edit }
        format.json { render json: @ebay_auth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ebay_auths/1
  # DELETE /ebay_auths/1.json
  def destroy
    @ebay_auth.destroy
    respond_to do |format|
      format.html { redirect_to ebay_auths_url, notice: 'Ebay auth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ebay_auth
      @ebay_auth = EbayAuth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ebay_auth_params
      params.require(:ebay_auth).permit(:user_id, :access_token, :refresh_token, :expiration, :token_type)
    end
end

app/helpers/ebay_auths_helper.rb
module EbayAuthsHelper
end

app/views/ebay_auths/_form.html.erb
<%= form_with(model: ebay_auth, local: true) do |form| %>
  <% if ebay_auth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ebay_auth.errors.count, "error") %> prohibited this ebay_auth from being saved:</h2>

      <ul>
      <% ebay_auth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :access_token %>
    <%= form.text_field :access_token %>
  </div>

  <div class="field">
    <%= form.label :refresh_token %>
    <%= form.text_field :refresh_token %>
  </div>

  <div class="field">
    <%= form.label :expiration %>
    <%= form.datetime_select :expiration %>
  </div>

  <div class="field">
    <%= form.label :token_type %>
    <%= form.text_field :token_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ebay_auths/edit.html.erb
<h1>Editing Ebay Auth</h1>

<%= render 'form', ebay_auth: @ebay_auth %>

<%= link_to 'Show', @ebay_auth %> |
<%= link_to 'Back', ebay_auths_path %>

app/views/ebay_auths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ebay Auths</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Access token</th>
      <th>Refresh token</th>
      <th>Expiration</th>
      <th>Token type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ebay_auths.each do |ebay_auth| %>
      <tr>
        <td><%= ebay_auth.user_id %></td>
        <td><%= ebay_auth.access_token %></td>
        <td><%= ebay_auth.refresh_token %></td>
        <td><%= ebay_auth.expiration %></td>
        <td><%= ebay_auth.token_type %></td>
        <td><%= link_to 'Show', ebay_auth %></td>
        <td><%= link_to 'Edit', edit_ebay_auth_path(ebay_auth) %></td>
        <td><%= link_to 'Destroy', ebay_auth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ebay Auth', new_ebay_auth_path %>

app/views/ebay_auths/new.html.erb
<h1>New Ebay Auth</h1>

<%= render 'form', ebay_auth: @ebay_auth %>

<%= link_to 'Back', ebay_auths_path %>

app/views/ebay_auths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @ebay_auth.user_id %>
</p>

<p>
  <strong>Access token:</strong>
  <%= @ebay_auth.access_token %>
</p>

<p>
  <strong>Refresh token:</strong>
  <%= @ebay_auth.refresh_token %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @ebay_auth.expiration %>
</p>

<p>
  <strong>Token type:</strong>
  <%= @ebay_auth.token_type %>
</p>

<%= link_to 'Edit', edit_ebay_auth_path(@ebay_auth) %> |
<%= link_to 'Back', ebay_auths_path %>

app/views/ebay_auths/token.html.erb
recibimos el token 