config/routes.rb
Rails.application.routes.draw do
  resources :lens_materials
  resources :lens_colors
  resources :frame_colors
  resources :models
  resources :frame_widths
  resources :costs do 
    collection {post :import}
  end
  resources :products do 
  	collection {post :traer_data}
  end
  resources :ebay_auths
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'welcome#index'


    get 'ebay_accept', to: 'welcome#ebay_accept'
    get '/token', to: 'ebay_auths#token'

    get '/productos', to: 'products#productos'
    get '/cargar_listings', to: 'products#cargar_listings'


    ### api 

    get '/get_item', to: 'ebay_auths#get_item'
    
    
end

app/models/frame_color.rb
class FrameColor < ApplicationRecord
	has_many :lens_colors
	belongs_to :model
end

app/controllers/frame_colors_controller.rb
class FrameColorsController < ApplicationController
  before_action :set_frame_color, only: [:show, :edit, :update, :destroy]

  # GET /frame_colors
  # GET /frame_colors.json
  def index
    @frame_colors = FrameColor.all
  end

  # GET /frame_colors/1
  # GET /frame_colors/1.json
  def show
  end

  # GET /frame_colors/new
  def new
    @frame_color = FrameColor.new
  end

  # GET /frame_colors/1/edit
  def edit
  end


  # POST /frame_colors
  # POST /frame_colors.json
  def create
    @frame_color = FrameColor.new(frame_color_params)
    frame_width_id = Model.find(frame_color_params["model_id"]).frame_width_id
    @frame_color.frame_width_id = frame_width_id


    respond_to do |format|
      if @frame_color.save
        format.html { redirect_to @frame_color, notice: 'Frame color was successfully created.' }
        format.json { render :show, status: :created, location: @frame_color }
      else
        format.html { render :new }
        format.json { render json: @frame_color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /frame_colors/1
  # PATCH/PUT /frame_colors/1.json
  def update
    respond_to do |format|
      if @frame_color.update(frame_color_params)
        format.html { redirect_to @frame_color, notice: 'Frame color was successfully updated.' }
        format.json { render :show, status: :ok, location: @frame_color }
      else
        format.html { render :edit }
        format.json { render json: @frame_color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /frame_colors/1
  # DELETE /frame_colors/1.json
  def destroy
    @frame_color.destroy
    respond_to do |format|
      format.html { redirect_to frame_colors_url, notice: 'Frame color was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_frame_color
      @frame_color = FrameColor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def frame_color_params
      params.require(:frame_color).permit(:frame_width_id, :model_id, :name)
    end
end

app/helpers/frame_colors_helper.rb
module FrameColorsHelper
end

app/views/frame_colors/_form.html.erb
<%= form_with(model: frame_color, local: true) do |form| %>
  <% if frame_color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(frame_color.errors.count, "error") %> prohibited this frame_color from being saved:</h2>

      <ul>
      <% frame_color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :model_id %>
    <%= form.collection_select :model_id, ::Model.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/frame_colors/edit.html.erb
<h1>Editing Frame Color</h1>

<%= render 'form', frame_color: @frame_color %>

<%= link_to 'Show', @frame_color %> |
<%= link_to 'Back', frame_colors_path %>

app/views/frame_colors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Frame Colors</h1>

<table>
  <thead>
    <tr>
      <th>Frame width</th>
      <th>Model</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @frame_colors.each do |frame_color| %>
      <tr>
        <td><%= frame_color.frame_width_id.present? ? FrameWidth.find(frame_color.frame_width_id).name : "" %></td>
        <td><%= FrameColor.find(frame_color.model_id).name %></td>
        <td><%= frame_color.name %></td>
        <td><%= link_to 'Show', frame_color %></td>
        <td><%= link_to 'Edit', edit_frame_color_path(frame_color) %></td>
        <td><%= link_to 'Destroy', frame_color, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Frame Color', new_frame_color_path %>

app/views/frame_colors/new.html.erb
<h1>New Frame Color</h1>

<%= render 'form', frame_color: @frame_color %>

<%= link_to 'Back', frame_colors_path %>

app/views/frame_colors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Frame width:</strong>
  <%= @frame_color.frame_width_id %>
</p>

<p>
  <strong>Model:</strong>
  <%= @frame_color.model_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @frame_color.name %>
</p>

<%= link_to 'Edit', edit_frame_color_path(@frame_color) %> |
<%= link_to 'Back', frame_colors_path %>