config/routes.rb
Rails.application.routes.draw do
  resources :lens_materials
  resources :lens_colors
  resources :frame_colors
  resources :models
  resources :frame_widths
  resources :costs do 
    collection {post :import}
  end
  resources :products do 
  	collection {post :traer_data}
  end
  resources :ebay_auths
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'welcome#index'


    get 'ebay_accept', to: 'welcome#ebay_accept'
    get '/token', to: 'ebay_auths#token'

    get '/productos', to: 'products#productos'
    get '/cargar_listings', to: 'products#cargar_listings'


    ### api 

    get '/get_item', to: 'ebay_auths#get_item'
    
    
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  def productos
    @products = Product.where("roi is not null").order(id: :asc)
  end

  def cargar_listings
  end

  def traer_data
    puts "entramos en traer_data"
    puts params 
    salida = {}

    existe = Product.find_by_url(params["url"])
    if existe.nil?
      producto = Product.new
      producto.url = params["url"]
      producto.average_price = params["precio_tp"]
      producto.average_sold = params["ventas_tp"]


      ebay_auth = EbayAuth.find(1)
      ## check expiration
      if (Time.now - ebay_auth.updated_at) >= 6600
        ## refresh token
        EbayAuth.refrescar_token(1)
        ebay_auth = EbayAuth.find(1)
      end

      authorization = EbayAuth.find(1).access_token

      url = params["url"]
      if url[0..26] == "https://www.ebay.com/itm/-/"
        item_id = url.gsub("https://www.ebay.com/itm/-/", "")
      elsif url[0..24] == "https://www.ebay.com/itm/"
        item_id = url.gsub("https://www.ebay.com/itm/", "")
      else
        item_id = url.gsub("http://www.ebay.com/itm/", "")
      end
      item_id = item_id[0..11]
      url_base = "https://api.ebay.com/buy/browse/v1/item/v1|#{item_id}|0"
      url_base = URI.encode(url_base.strip)
      header    = {"Content-Type" => "application/json" ,"Authorization" => "Bearer #{authorization}"}

      parametros = {}
      puts parametros

      response = HTTParty.get("#{url_base}", :query => parametros, :headers =>header)
      if response.code == 200 
        res = JSON.parse response.body
        puts res
        atributos = res["localizedAspects"]
        upc = "no hay UPC"
        # producto = Product.find(params["product_id"].gsub("product_", ""))
        producto.name = res["title"]
        producto.current_price = res["price"]["value"]
        producto.upc = res["gtin"]
        if producto.upc.nil? && atributos.present? && atributos.size > 0
          atributos.each do |x|
            if x["name"] =="UPC"
              upc = x["value"]
              producto.upc = upc
            end
          end
        end
        if res["estimatedAvailabilities"].present? && res["estimatedAvailabilities"][0]["estimatedSoldQuantity"].present? 
          producto.total_sold = res["estimatedAvailabilities"][0]["estimatedSoldQuantity"].to_i
        end
        salida["UPC"] = upc
      else
        puts response.code
        puts response.body
        salida["error"] = "item no encontrado"
      end
      producto.save
      if producto.upc.present? 
        x = producto 
        costo = Cost.find_by_upc(x.upc)
        if costo.present? 
          x.cost = costo.precio_esp.to_f
          x.gross_margin = x.current_price - costo.precio_esp
          x.net_margin = (x.current_price.to_f*0.88)- 5 - costo.precio_esp.to_f
          x.roi = ((x.net_margin + x.cost)/x.cost)-1
          x.save 
        end
      end
    else
      salida["error"] = "duplicado"
    end


    respond_to do |format|
      puts "entro en get items"
      puts salida
      format.json { render json: salida }
    end
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:url, :upc, :current_price, :average_price, :cost, :gross_margin, :net_margin, :roi, :name, :total_sold, :average_sold)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :upc %>
    <%= form.text_field :upc %>
  </div>

  <div class="field">
    <%= form.label :current_price %>
    <%= form.text_field :current_price %>
  </div>

  <div class="field">
    <%= form.label :average_price %>
    <%= form.text_field :average_price %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="field">
    <%= form.label :gross_margin %>
    <%= form.text_field :gross_margin %>
  </div>

  <div class="field">
    <%= form.label :net_margin %>
    <%= form.text_field :net_margin %>
  </div>

  <div class="field">
    <%= form.label :roi %>
    <%= form.text_field :roi %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :total_sold %>
    <%= form.number_field :total_sold %>
  </div>

  <div class="field">
    <%= form.label :average_sold %>
    <%= form.number_field :average_sold %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/cargar_listings.html.erb
<% if (params["password"].present? && params["password"] == password = ENV.fetch('PASSWORD'))%> 

<div class="container">
	<h3>Copia y el pega el link de la publicacion de Ebay en este espacio y presiona Enter para guardar</h3>
	<div>
		<input id="precio_tp" placeholder="Average Sale Price"> | 
		<input id="ventas_tp" placeholder="Items Sold"> | 
		<input id="nuevo_url" onkeypress="if (window.event.keyCode == 13) traerData()" placeholder="https://www.ebay.com...">
	</div>
	<div id="status">
	</div>
</div>

<br>
<%= link_to 'Ver Listado', productos_path(:password => params["password"]) %>


<script>


	function traerData(){
    console.log("entramos en traerData ")
    var url = $('#nuevo_url').val();
    var precio_tp = $('#precio_tp').val();
    var ventas_tp = $('#ventas_tp').val();
    
    $.ajax({
      type:"POST", 
      url:"<%= url_for traer_data_products_path(:id => 33)%>", 
      data: {url:url, precio_tp: precio_tp, ventas_tp: ventas_tp, "authenticity_token": AUTH_TOKEN },
      dataType: 'json',
      success:function(result){
        console.log("listo ")
        console.log(result)
        $('#nuevo_url').val('');
        $('#precio_tp').val('');
        $('#ventas_tp').val('');
      }
    });
  };


</script>

<% else %> 
Acceso no Autorizado 

<% end %> 

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% if (params["password"].present? && params["password"] == password = ENV.fetch('PASSWORD')) %> 
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Upc</th>
      <th>Current price</th>
      <th>Average price</th>
      <th>Cost</th>
      <th>Gross margin</th>
      <th>Net margin</th>
      <th>Roi</th>
      <th>Name</th>
      <th>Total sold</th>
      <th>Average sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.url %></td>
        <td><%= product.upc %></td>
        <td><%= product.current_price %></td>
        <td><%= product.average_price %></td>
        <td><%= product.cost %></td>
        <td><%= product.gross_margin %></td>
        <td><%= product.net_margin %></td>
        <td><%= product.roi %></td>
        <td><%= product.name %></td>
        <td><%= product.total_sold %></td>
        <td><%= product.average_sold %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

<% else %>

Acceso no Autorizado 

<% end %> 

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/productos.html.erb
<% if (params["password"].present? && params["password"] == password = ENV.fetch('PASSWORD')) || 2 == 2%> 

<nav class="navbar navbar-inverse navbar-fixed-top">
  <a href="">Insert Brand / Logo</a>
</nav>
<section class="content-area">
  <div class="table-area">

	<%= link_to 'Cargar Listing', cargar_listings_path(:password => params["password"]) %>
	<div class="table-wrapper-scroll-y">
		 <table class="responsive-table table">
			<thead>
				<th >URL</th>
				<th >UPC</th>
				<th>Ventas Terapeak</th>
				<th>Precio Actual</th>
				<th>Precio Terapeak</th>
				<th>Precio LP</th>
				<th>Margen Bruto</th>
				<th>Margen Neto</th>
				<th>ROI %</th>
				<th>Name</th>
			</thead>
			<tbody>
				<% @products.each do |p| %> 
					<tr>
						<td >
						<% if p.url.nil? %> 
							
								<input placeholder="url de la publicacion" id="product_<%= p.id %>" onchange="traerData('product_<%=p.id %>')">
								<p id="guardado_<%= p.id %>" class="hidden">Guardado!</p>
						<% else %> 
							<a href="<%= p.url %>" target="_blank">Ver Publicacion</a>
						<% end %> 
						</td>
						<td><%= p.upc %></td>
						<th><%= p.average_sold %></th>
						<th><%= p.current_price %></th>
						<th><%= p.average_price %></th>
						<th><%= p.cost %></th>
						<th><%= p.gross_margin.present? ? p.gross_margin.round(2) : "" %></th>
						<th><%= p.net_margin.present? ? p.net_margin.round(2) : "" %></th>
						<th><%= p.roi.present? ? 100*p.roi.round(4) : "" %><%= p.roi.present? ? "%" : "" %> </th>
						<th><%= p.name %></th>
					</tr>
				<% end %> 
			</tbody>
		</table>
	</div>
</div>


<style>
body {
  padding-top: 50px;
}

.navbar {
  height: 50px;
  padding: 0 15px;
  width: 100%;
  position: fixed;
  top: 0;
  z-index: 1;
}

.navbar a {
  color: white;
  line-height: 3em;
}

.table-area {
  position: relative;
  z-index: 0;
  margin-top: 50px;
}

table.responsive-table {
  display: table;
  /* required for table-layout to be used (not normally necessary; included for completeness) */
  table-layout: fixed;
  /* this keeps your columns with fixed with exactly the right width */
  width: 100%;
  /* table must have width set for fixed layout to work as expected */
  height: 100%;
}

table.responsive-table thead {
  position: fixed;
  top: 50px;
  left: 0;
  right: 0;
  width: 100%;
  height: 50px;
  line-height: 3em;
  background: #eee;
  table-layout: fixed;
  display: table;
}

table.responsive-table th {
  background: #eee;
}

table.responsive-table td {
  line-height: 2em;
}

table.responsive-table tr > td,
table.responsive-table th {
  text-align: left;
}



</style>


<% else %> 
Acceso no autorizado 

<% end %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @product.url %>
</p>

<p>
  <strong>Upc:</strong>
  <%= @product.upc %>
</p>

<p>
  <strong>Current price:</strong>
  <%= @product.current_price %>
</p>

<p>
  <strong>Average price:</strong>
  <%= @product.average_price %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @product.cost %>
</p>

<p>
  <strong>Gross margin:</strong>
  <%= @product.gross_margin %>
</p>

<p>
  <strong>Net margin:</strong>
  <%= @product.net_margin %>
</p>

<p>
  <strong>Roi:</strong>
  <%= @product.roi %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Total sold:</strong>
  <%= @product.total_sold %>
</p>

<p>
  <strong>Average sold:</strong>
  <%= @product.average_sold %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>